import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { cx } from '@/styled-system/css'
import { verticalScroll } from '@/styled-system/recipes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const bodyClassname = cx(inter.className, verticalScroll())

  return (
    <html lang="en">
      <body className={bodyClassname}>{children}</body>
    </html>
  )
}
